if(${CMAKE_BUILD_TYPE} MATCHES Debug)
    message("Debug mode")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -march=native -O0 -g -Wall -Wextra -fopenmp")
else()
    message("Release mode")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -march=native -O3 -Wall -Wextra -fopenmp")
endif()
